webtalk_init -webtalk_dir /home/shmilybelon/Desktop/digital_logic/exp3_4/sd3_2/sd3_2.sim/sim_1/impl/timing/xsim/xsim.dir/sd3_2_tb_time_impl/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Jun  7 22:12:04 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2086221" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "b6c21fff-1dc0-427b-8652-cf61bd3066ff" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "f7557401741146359bd80df5404fd6f5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Deepin" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Deepin 15.5" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2300.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "129300_KB" -context "xsim\\usage"
webtalk_transmit -clientid 386631175 -regid "" -xml /home/shmilybelon/Desktop/digital_logic/exp3_4/sd3_2/sd3_2.sim/sim_1/impl/timing/xsim/xsim.dir/sd3_2_tb_time_impl/webtalk/usage_statistics_ext_xsim.xml -html /home/shmilybelon/Desktop/digital_logic/exp3_4/sd3_2/sd3_2.sim/sim_1/impl/timing/xsim/xsim.dir/sd3_2_tb_time_impl/webtalk/usage_statistics_ext_xsim.html -wdm /home/shmilybelon/Desktop/digital_logic/exp3_4/sd3_2/sd3_2.sim/sim_1/impl/timing/xsim/xsim.dir/sd3_2_tb_time_impl/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
