#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2017.4 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Jun 07 21:15:17 CST 2018
# SW Build 2086221 on Fri Dec 15 20:54:30 MST 2017
#
# Copyright 1986-2017 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
ExecStep()
{
"$@"
RETVAL=$?
if [ $RETVAL -ne 0 ]
then
exit $RETVAL
fi
}
ExecStep xsim sd3_2_tb_time_impl -key {Post-Implementation:sim_1:Timing:sd3_2_tb} -tclbatch sd3_2_tb.tcl -view /home/shmilybelon/Desktop/digital_logic/exp3_4/sd3_2/sd3_2_tb_behav.wcfg -log simulate.log
